In [1]:
import numpy as np 
import itertools

# Graph Representation ~ Question 1

In [2]:
class GRF_File:
    def __init__(self):
        pass
    def file_import(self, file):
        f = open(file)
        str_data = f.readlines() # read all lines and save into str_data
        data = [[float(element) for element in str.split()] \
            for str in str_data]
        for row in data:
            del row[1]
            del row[1]
        self.data = data
        print("Data collected!")
    
    def edge_list(self):
        data = self.data # imports the data from the file
        results = [] # empty list to keep final coordinates
        
        for count, record in enumerate(data): #leeping count of each list in data, storing each list in "record"
            for num in record:
                index = int(record[0]) #taking the first index of each "record"
                first = [index, int(num)] # putting the coordinates of the index and the next number in the list
                if int(num) > index: #NOT allowing iterations
                    results.append(first) 
        self.results = results
        return results
                      
    def adjacency_matrix(self):  
        data = self.data #imports the data from the file
        rows, columns = len(data), len(data) #taking the length of the data to create row and column vector
        matrices = np.zeros([rows,columns]) # printing matrix of zeros
        
        for count, record in enumerate(data):
            for num in record[1:]:
                num = int(num)
                matrices[count][num-1] = 1
        return matrices
    
    def incidence_matrix(self):
        results = self.results #importing results from edge list
        data = self.data #importing the data from the file
        rows, columns = len(results), len(data) #the rows equal the length of results and the columns = length of data
        matrix = np.zeros([rows, columns]) #matrix of zeros with row and columns
        
        for count, record in enumerate(results): 
            for m, num in enumerate(record):
                num = int(num)
                matrix[count][num-1] = 1
        return matrix
    
    def adjacency_structure(self):
        data = self.data
        for count,number in enumerate(data, 1):
            print(f"G{ {count} } = {number[1:]}")

In [3]:
test = GRF_File()
test.file_import('graph.grf') #you can put any file with the same format as the file in this object

Data collected!


In [4]:
test.edge_list()

[[1, 2], [1, 3], [2, 3], [3, 4]]

In [5]:
test.adjacency_matrix()

array([[0., 1., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
test.adjacency_structure()

G{1} = [2.0, 3.0]
G{2} = [1.0, 3.0]
G{3} = [1.0, 2.0, 4.0]
G{4} = [3.0]
G{5} = []


In [7]:
test.incidence_matrix()

array([[1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0.]])

# Question 1 ~ i

In [8]:
#Alphabetized
#1. Argentina
#2. Bolivia
#3. Brasil
#4. Chile
#5. Colombia
#6. Ecuador
#7. Guyana
#8. Paraguay
#9. Peru
#10. Suriname
#11. Uruguay
#12. Venezuela

# Question 1 ~ ii

In [9]:
countries = GRF_File()
countries.file_import('countries.grf') #you can put any file with the same format as the file in this object

Data collected!


In [10]:
countries.edge_list()

[[1, 2],
 [1, 3],
 [1, 4],
 [1, 8],
 [1, 11],
 [2, 3],
 [2, 4],
 [2, 8],
 [2, 9],
 [3, 5],
 [3, 7],
 [3, 8],
 [3, 9],
 [3, 10],
 [3, 11],
 [3, 12],
 [4, 9],
 [5, 6],
 [5, 9],
 [5, 12],
 [6, 9],
 [7, 10],
 [7, 12]]

In [11]:
countries.adjacency_matrix()

array([[0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.]])

In [12]:
countries.adjacency_structure()

G{1} = [2.0, 3.0, 4.0, 8.0, 11.0]
G{2} = [1.0, 3.0, 4.0, 8.0, 9.0]
G{3} = [1.0, 2.0, 5.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0]
G{4} = [1.0, 2.0, 9.0]
G{5} = [3.0, 6.0, 9.0, 12.0]
G{6} = [5.0, 9.0]
G{7} = [3.0, 10.0, 12.0]
G{8} = [1.0, 2.0, 3.0]
G{9} = [2.0, 3.0, 4.0, 5.0, 6.0]
G{10} = [3.0, 7.0]
G{11} = [1.0, 3.0]
G{12} = [3.0, 5.0, 7.0]


In [13]:
countries.incidence_matrix()

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1.,

# Question 1 ~ iii

In [15]:
A = countries.adjacency_matrix()
Chile = [0,0,0,1,0,0,0,0,0,0,0,0]
two = np.dot(A, Chile)
three = np.dot(A, two)
four = np.dot(A, three)
four

array([11., 10.,  8.,  4.,  5.,  2.,  3.,  6., 10.,  3.,  4.,  4.])

In [16]:
#Answer: You must vist at least 4 countries.

#Answer: There are 4 shortest paths
#4/9/5/12 :: Chile->Peru->Columbia->Venezuela
#4/9/3/12 :: Chile->Peru->Brasil->Venezuela
#4/2/3/12 :: Chile->Bolivia->Brasil->Venezuela
#4/1/3/12 :: Chile->Argentina->Brasil->Venezuela
bl = np.linalg.matrix_power(A, 3).dot(Chile)
bl

array([11., 10.,  8.,  4.,  5.,  2.,  3.,  6., 10.,  3.,  4.,  4.])

# Question 1 ~ iv

In [17]:
eight_walks = np.linalg.matrix_power(A, 8).dot(Chile)
eight_walks

array([14789., 15989., 22207., 10088., 11106.,  5650.,  8195., 11604.,
       14042.,  6522.,  8061.,  8972.])

In [18]:
eight_walks.sum()

137225.0