# QUESTION #1 Part A

In [1]:
import numpy as np

l = np.zeros((10), dtype=int)
l[4] = 1

print(l)

[0 0 0 0 1 0 0 0 0 0]


# QUESTION #1 Part B

In [2]:
import numpy as np

z = np.arange(1, 13).reshape((3,4))

print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# QUESTION #1 Part C

In [3]:
import numpy as np

n = 10

p = np.full((n, n), 0)

p[1:n-1,1:n-1] = 1

print(p)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


# QUESTION 2 Part A

In [4]:
import numpy as np

z = 2 ** np.arange(1, 12)

print(z)

[   2    4    8   16   32   64  128  256  512 1024 2048]


# Question #2 Part B

In [5]:
import numpy as np

n = np.array([[0.1, 0.8, 0.8],
             [0.2, 0.4, 1.1],
             [1.3, 0.9, 1.1]])
np.average(n)
#print(n)

0.7444444444444444

# QUESTION #2 Part C

In [6]:
import numpy as np

n = np.array([[0.1, 0.8, 0.8],
             [0.2, 0.4, 1.1],
             [1.3, 0.9, 1.1]])

np.average(n, axis=0)
    

array([0.53333333, 0.7       , 1.        ])

# QUESTION #3

In [7]:
import numpy as np
xn = np.array([0.        , 0.62831853, 
              1.25663706, 1.88495559, 
              2.51327412, 3.14159265, 
              3.76991118, 4.39822972, 
              5.02654825, 5.65486678,
              6.28318531])

yn = np.array([0.            ,  5.87785252e-01,  
              9.51056516e-01,  9.51056516e-01, 
              5.87785252e-01,  1.22464680e-16, 
              -5.87785252e-01, -9.51056516e-01,
              -9.51056516e-01, -5.87785252e-01, 
              -2.44929360e-16])


        
def linear_interpolation(x,xn,yn):
    for i in range(len(xn) - 1):
        if xn[i] < x <= xn[i+1]:
            j = i
            break
    A = (xn[i+1] - x) / (xn[i+1] - xn[i])
    B = (x - xn[i]) / (xn[i+1] - xn[i])
            
    return (A*yn[i] + B*yn[i+1])

print(linear_interpolation(2.1,xn,yn))

0.8267255422869786


# Question #4

In [8]:
import numpy as np
from math import exp

f = lambda x: 5*x**2 + 9 *x - 80

def bisection_method(f, a = 3, b = 4 , epsilon = 1e-6):
    while abs(a-b) >= epsilon:
        midpoint = (np.sign(a)+b) / 2
        hold = f(b)*f(midpoint) 
        if hold > epsilon:
            a = midpoint
        else:
            b = midpoint
            
        return midpoint

print(bisection_method(f))

2.5
